// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendURL() {
  return window['go']['main']['App']['BackendURL']();
}

export function InitialPath() {
  return window['go']['main']['App']['InitialPath']();
}

export function IsChildWindow() {
  return window['go']['main']['App']['IsChildWindow']();
}

export function OpenClientWindow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenClientWindow'](arg1, arg2, arg3, arg4, arg5);
}

export function WaitForBackend(arg1) {
  return window['go']['main']['App']['WaitForBackend'](arg1);
}
