// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendURL():Promise<string>;

export function InitialPath():Promise<string>;

export function IsChildWindow():Promise<boolean>;

export function OpenClientWindow(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function WaitForBackend(arg1:number):Promise<void>;
